### ISSUE TITLE
اعداد صحیح و کاربرد آن‌ها در تعیین اختلاف زمانی بین مناطق مختلف جهان 

### ISSUE THREAD

**Issue by fahimeh-jm** [learn-hub/IdeaPool#44]
### Idea Title

کاربردی از اعداد صحیح

### Relevant/Source Link (video, book, etc.)

 مجموعه کتاب های علامه حلی --ریاضی هفتم

### Specific Section of the Source (e.g., start/end time for videos or page numbers for books)

  فصل دوم اعداد صحیح -- ریاضی هفتم

### Summary/Synopsis

ساعت هماهنگ جهانی یک استاندارد زمان اتمی برای تعیین ساعت ها و اختلاف زمانی در سراسر جهان است. به کمک مبدا می توانیم اختلاف ساعت هر نقطه از زمین با مبدا را به صورت یک عدد مثبت یا منفی نمایش دهیم. البته این اختلاف ها لزوما صحیح نیستند مثلا ممکن است یک نقطه 3.5 ساعت با مبدا  اختلاف زمان داشته باشد.

### Main Idea

![20241005_204137](https://github.com/user-attachments/assets/7f74ad48-15d7-4d41-af7d-0f607dea0a2d)
برای تعیین زمان دقیق در نقاط مختلف جهان، از اعداد صحیح استفاده می‌کنیم. هر نقطه جغرافیایی در نقشه یک اختلاف زمانی (مثبت یا منفی) نسبت به گرینویچ دارد. این اختلاف زمانی با اعداد صحیح نمایش داده می‌شود. برای مثال:

اگر در تهران ساعت 12 ظهر باشد و اختلاف زمانی تهران با لندن +3:30 باشد، یعنی زمان در تهران 3 ساعت و 30 دقیقه جلوتر از لندن است.
اگر در نیویورک ساعت 9 صبح باشد و اختلاف زمانی آن با لندن 5- باشد، یعنی نیویورک 5 ساعت عقب‌تر از لندن است.

اعداد مثبت نشان‌دهنده مناطق زمانی هستند که جلوتر از گرینویچ هستند و اعداد منفی نشان‌دهنده مناطقی هستند که عقب‌تر از گرینویچ قرار دارند. برای محاسبه اختلاف زمانی بین دو منطقه، می‌توانیم از جمع یا تفریق اعداد صحیح استفاده کنیم

### Idea Type

Application

### Main Educational Subject Area

math--arithmetic (M-A)

### Education Level (difficulty level)

elementary and above

### Educational Sub-Category

زمان --  ساعت هماهنگ جهانی -- نصف النهار

### Main Topics

اعداد منفی و مثبت

### Other Related Topics

فاصله زمانی -- زمان 

### FAQ

رای پیدا کردن اختلاف زمانی بین تهران و نیویورک:

اختلاف زمانی تهران: +3:30
اختلاف زمانی نیویورک: 5-
3:30 -(-5) =8:30
بنابراین، تهران 8 ساعت و 30 دقیقه جلوتر از نیویورک است.

### Overall Score

9

### Usefulness Score

9

### Ease of Understanding Score

9

### Contact Information

jabarifahimeh.2016@gmail.com

### Code of Conduct Agreement

- [X] I agree to follow this project's Code of Conduct

**Comment by learn-hub** [comment]
duplicate of https://github.com/learn-hub/IdeaPool/issues/45
